# Generated by Django 4.1.5 on 2023-01-19 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_creator_event_user_event_attendees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 12, 38, 11, 398266)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 12, 38, 11, 398248)),
        ),
    ]
