# Generated by Django 4.1.5 on 2023-01-19 12:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_calendar_summary_alter_event_end_alter_event_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calendar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.calendar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 12, 51, 43, 954499)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 12, 51, 43, 954482)),
        ),
    ]
