# Generated by Django 4.1.5 on 2023-01-19 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_description_alter_event_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 16, 36, 55, 80205)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 16, 36, 55, 80189)),
        ),
    ]
