# Generated by Django 4.1.5 on 2023-01-20 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_credentials_googlecredential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlecredential',
            name='client_secret',
        ),
        migrations.RemoveField(
            model_name='googlecredential',
            name='token_uri',
        ),
    ]
